#!/bin/bash

echo "🎵 iPhone에 Shortcuts 설정하기"
echo "================================"
echo ""
echo "1단계: iPhone에서 Shortcuts 앱 열기"
echo ""
echo "2단계: + 버튼 눌러서 새 단축어 만들기"
echo ""
echo "3단계: 액션 추가 (순서대로):"
echo ""
echo "   [액션 1] URL 가져오기"
echo "   ────────────────────────────"
echo "   • 검색창에 'URL' 입력"
echo "   • 'URL 가져오기' 선택"
echo "   • URL 입력: http://192.168.219.1:8800/speaker_2.wav"
echo "   • (Mac IP는 자동으로 감지됩니다)"
echo ""
echo "   [액션 2] URL 콘텐츠 가져오기" 
echo "   ────────────────────────────"
echo "   • 검색창에 'URL 콘텐츠' 입력"
echo "   • 'URL 콘텐츠 가져오기' 선택"
echo "   • 입력: 이전 액션의 URL"
echo ""
echo "   [액션 3] 미디어 재생"
echo "   ────────────────────────────"
echo "   • 검색창에 '미디어 재생' 입력"
echo "   • '미디어 재생' 선택"
echo "   • 입력: 이전 액션의 콘텐츠"
echo ""
echo "4단계: 단축어 이름 설정"
echo "   • 상단의 '새로운 단축어' 클릭"
echo "   • 이름 변경: Play Audio"
echo "   • 완료 버튼 클릭"
echo ""
echo "5단계: 테스트"
echo "   • Shortcuts 앱에서 'Play Audio' 클릭"
echo "   • 오디오가 재생되는지 확인"
echo ""
echo "================================"
echo "✅ 설정이 완료되면 Tauri 앱에서 테스트를 실행하세요!"
echo ""
echo "💡 Mac IP 자동 감지 중..."

# Mac의 로컬 IP 찾기
MAC_IP=$(ipconfig getifaddr en0 || ipconfig getifaddr en1)

if [ -z "$MAC_IP" ]; then
    echo "⚠️  Mac IP를 찾을 수 없습니다. Wi-Fi에 연결되어 있는지 확인하세요."
else
    echo "✅ Mac IP: $MAC_IP"
    echo ""
    echo "Shortcuts URL을 다음으로 변경하세요:"
    echo "http://${MAC_IP}:8800/speaker_2.wav"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "고급 사용: URL Scheme으로 Shortcuts 실행"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Safari 주소창에 입력하여 테스트:"
echo "shortcuts://run-shortcut?name=Play%20Audio"
echo ""
